// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7dc4d5d85c
// Version Date: Mon May 28 22:12:59 UTC 2018

package cli

import (
	"test/truss/test-service/svc/server"
)

// Config will be populated by ENV vars on initilization
// flags will overwrite ENV vars in Config on flag.Parse()
var Config server.Config

func init() {
	Config.GRPCAddr = "127.0.0.1:8888"
	Config.DebugAddr = "127.0.0.1:8889"
}
