// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommonReq struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonReq) Reset()         { *m = CommonReq{} }
func (m *CommonReq) String() string { return proto.CompactTextString(m) }
func (*CommonReq) ProtoMessage()    {}
func (*CommonReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{0}
}
func (m *CommonReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonReq.Unmarshal(m, b)
}
func (m *CommonReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonReq.Marshal(b, m, deterministic)
}
func (dst *CommonReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonReq.Merge(dst, src)
}
func (m *CommonReq) XXX_Size() int {
	return xxx_messageInfo_CommonReq.Size(m)
}
func (m *CommonReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonReq.DiscardUnknown(m)
}

var xxx_messageInfo_CommonReq proto.InternalMessageInfo

func (m *CommonReq) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CommonReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CommonRsp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonRsp) Reset()         { *m = CommonRsp{} }
func (m *CommonRsp) String() string { return proto.CompactTextString(m) }
func (*CommonRsp) ProtoMessage()    {}
func (*CommonRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{1}
}
func (m *CommonRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonRsp.Unmarshal(m, b)
}
func (m *CommonRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonRsp.Marshal(b, m, deterministic)
}
func (dst *CommonRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonRsp.Merge(dst, src)
}
func (m *CommonRsp) XXX_Size() int {
	return xxx_messageInfo_CommonRsp.Size(m)
}
func (m *CommonRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CommonRsp proto.InternalMessageInfo

func (m *CommonRsp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CommonRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AccountInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName          string   `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{2}
}
func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfo.Unmarshal(m, b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
}
func (dst *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(dst, src)
}
func (m *AccountInfo) XXX_Size() int {
	return xxx_messageInfo_AccountInfo.Size(m)
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AccountInfo) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AccountInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AccountInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccountInfo) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type SetSessionUserDataRsp struct {
	Common               *CommonRsp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetSessionUserDataRsp) Reset()         { *m = SetSessionUserDataRsp{} }
func (m *SetSessionUserDataRsp) String() string { return proto.CompactTextString(m) }
func (*SetSessionUserDataRsp) ProtoMessage()    {}
func (*SetSessionUserDataRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{3}
}
func (m *SetSessionUserDataRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSessionUserDataRsp.Unmarshal(m, b)
}
func (m *SetSessionUserDataRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSessionUserDataRsp.Marshal(b, m, deterministic)
}
func (dst *SetSessionUserDataRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSessionUserDataRsp.Merge(dst, src)
}
func (m *SetSessionUserDataRsp) XXX_Size() int {
	return xxx_messageInfo_SetSessionUserDataRsp.Size(m)
}
func (m *SetSessionUserDataRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSessionUserDataRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SetSessionUserDataRsp proto.InternalMessageInfo

func (m *SetSessionUserDataRsp) GetCommon() *CommonRsp {
	if m != nil {
		return m.Common
	}
	return nil
}

type GetSessionUserDataReq struct {
	Common               *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetSessionUserDataReq) Reset()         { *m = GetSessionUserDataReq{} }
func (m *GetSessionUserDataReq) String() string { return proto.CompactTextString(m) }
func (*GetSessionUserDataReq) ProtoMessage()    {}
func (*GetSessionUserDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{4}
}
func (m *GetSessionUserDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionUserDataReq.Unmarshal(m, b)
}
func (m *GetSessionUserDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionUserDataReq.Marshal(b, m, deterministic)
}
func (dst *GetSessionUserDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionUserDataReq.Merge(dst, src)
}
func (m *GetSessionUserDataReq) XXX_Size() int {
	return xxx_messageInfo_GetSessionUserDataReq.Size(m)
}
func (m *GetSessionUserDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionUserDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionUserDataReq proto.InternalMessageInfo

func (m *GetSessionUserDataReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

type GetSessionUserDataRsp struct {
	Common               *CommonRsp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	UserData             string     `protobuf:"bytes,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetSessionUserDataRsp) Reset()         { *m = GetSessionUserDataRsp{} }
func (m *GetSessionUserDataRsp) String() string { return proto.CompactTextString(m) }
func (*GetSessionUserDataRsp) ProtoMessage()    {}
func (*GetSessionUserDataRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{5}
}
func (m *GetSessionUserDataRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionUserDataRsp.Unmarshal(m, b)
}
func (m *GetSessionUserDataRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionUserDataRsp.Marshal(b, m, deterministic)
}
func (dst *GetSessionUserDataRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionUserDataRsp.Merge(dst, src)
}
func (m *GetSessionUserDataRsp) XXX_Size() int {
	return xxx_messageInfo_GetSessionUserDataRsp.Size(m)
}
func (m *GetSessionUserDataRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionUserDataRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionUserDataRsp proto.InternalMessageInfo

func (m *GetSessionUserDataRsp) GetCommon() *CommonRsp {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *GetSessionUserDataRsp) GetUserData() string {
	if m != nil {
		return m.UserData
	}
	return ""
}

type LoginReq struct {
	Common               *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	UserName             string     `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string     `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{6}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (dst *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(dst, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *LoginReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRsp struct {
	Common               *CommonRsp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Token                string     `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{7}
}
func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (dst *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(dst, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetCommon() *CommonRsp {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *LoginRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutReq struct {
	Common               *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{8}
}
func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (dst *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(dst, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

func (m *LogoutReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

type LogoutRsp struct {
	Common               *CommonRsp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LogoutRsp) Reset()         { *m = LogoutRsp{} }
func (m *LogoutRsp) String() string { return proto.CompactTextString(m) }
func (*LogoutRsp) ProtoMessage()    {}
func (*LogoutRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{9}
}
func (m *LogoutRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRsp.Unmarshal(m, b)
}
func (m *LogoutRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRsp.Marshal(b, m, deterministic)
}
func (dst *LogoutRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRsp.Merge(dst, src)
}
func (m *LogoutRsp) XXX_Size() int {
	return xxx_messageInfo_LogoutRsp.Size(m)
}
func (m *LogoutRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRsp proto.InternalMessageInfo

func (m *LogoutRsp) GetCommon() *CommonRsp {
	if m != nil {
		return m.Common
	}
	return nil
}

type GetSessionInfoReq struct {
	Common               *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetSessionInfoReq) Reset()         { *m = GetSessionInfoReq{} }
func (m *GetSessionInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetSessionInfoReq) ProtoMessage()    {}
func (*GetSessionInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{10}
}
func (m *GetSessionInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionInfoReq.Unmarshal(m, b)
}
func (m *GetSessionInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionInfoReq.Marshal(b, m, deterministic)
}
func (dst *GetSessionInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionInfoReq.Merge(dst, src)
}
func (m *GetSessionInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetSessionInfoReq.Size(m)
}
func (m *GetSessionInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionInfoReq proto.InternalMessageInfo

func (m *GetSessionInfoReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

type GetSessionInfoRsp struct {
	Common               *CommonRsp   `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	AccountInfo          *AccountInfo `protobuf:"bytes,2,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetSessionInfoRsp) Reset()         { *m = GetSessionInfoRsp{} }
func (m *GetSessionInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetSessionInfoRsp) ProtoMessage()    {}
func (*GetSessionInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{11}
}
func (m *GetSessionInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionInfoRsp.Unmarshal(m, b)
}
func (m *GetSessionInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionInfoRsp.Marshal(b, m, deterministic)
}
func (dst *GetSessionInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionInfoRsp.Merge(dst, src)
}
func (m *GetSessionInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetSessionInfoRsp.Size(m)
}
func (m *GetSessionInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionInfoRsp proto.InternalMessageInfo

func (m *GetSessionInfoRsp) GetCommon() *CommonRsp {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *GetSessionInfoRsp) GetAccountInfo() *AccountInfo {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

type SetSessionUserDataReq struct {
	Common               *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	UserData             string     `protobuf:"bytes,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetSessionUserDataReq) Reset()         { *m = SetSessionUserDataReq{} }
func (m *SetSessionUserDataReq) String() string { return proto.CompactTextString(m) }
func (*SetSessionUserDataReq) ProtoMessage()    {}
func (*SetSessionUserDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{12}
}
func (m *SetSessionUserDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSessionUserDataReq.Unmarshal(m, b)
}
func (m *SetSessionUserDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSessionUserDataReq.Marshal(b, m, deterministic)
}
func (dst *SetSessionUserDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSessionUserDataReq.Merge(dst, src)
}
func (m *SetSessionUserDataReq) XXX_Size() int {
	return xxx_messageInfo_SetSessionUserDataReq.Size(m)
}
func (m *SetSessionUserDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSessionUserDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetSessionUserDataReq proto.InternalMessageInfo

func (m *SetSessionUserDataReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *SetSessionUserDataReq) GetUserData() string {
	if m != nil {
		return m.UserData
	}
	return ""
}

type RegisterAppReq struct {
	Common               *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	AppName              string     `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppRedirectId        string     `protobuf:"bytes,3,opt,name=app_redirect_id,json=appRedirectId,proto3" json:"app_redirect_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterAppReq) Reset()         { *m = RegisterAppReq{} }
func (m *RegisterAppReq) String() string { return proto.CompactTextString(m) }
func (*RegisterAppReq) ProtoMessage()    {}
func (*RegisterAppReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{13}
}
func (m *RegisterAppReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAppReq.Unmarshal(m, b)
}
func (m *RegisterAppReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAppReq.Marshal(b, m, deterministic)
}
func (dst *RegisterAppReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAppReq.Merge(dst, src)
}
func (m *RegisterAppReq) XXX_Size() int {
	return xxx_messageInfo_RegisterAppReq.Size(m)
}
func (m *RegisterAppReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAppReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAppReq proto.InternalMessageInfo

func (m *RegisterAppReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *RegisterAppReq) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *RegisterAppReq) GetAppRedirectId() string {
	if m != nil {
		return m.AppRedirectId
	}
	return ""
}

type RegisterAppRsp struct {
	Common               *CommonRsp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterAppRsp) Reset()         { *m = RegisterAppRsp{} }
func (m *RegisterAppRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterAppRsp) ProtoMessage()    {}
func (*RegisterAppRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{14}
}
func (m *RegisterAppRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAppRsp.Unmarshal(m, b)
}
func (m *RegisterAppRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAppRsp.Marshal(b, m, deterministic)
}
func (dst *RegisterAppRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAppRsp.Merge(dst, src)
}
func (m *RegisterAppRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterAppRsp.Size(m)
}
func (m *RegisterAppRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAppRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAppRsp proto.InternalMessageInfo

func (m *RegisterAppRsp) GetCommon() *CommonRsp {
	if m != nil {
		return m.Common
	}
	return nil
}

type UnRegisterAppReq struct {
	Common               *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UnRegisterAppReq) Reset()         { *m = UnRegisterAppReq{} }
func (m *UnRegisterAppReq) String() string { return proto.CompactTextString(m) }
func (*UnRegisterAppReq) ProtoMessage()    {}
func (*UnRegisterAppReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{15}
}
func (m *UnRegisterAppReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnRegisterAppReq.Unmarshal(m, b)
}
func (m *UnRegisterAppReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnRegisterAppReq.Marshal(b, m, deterministic)
}
func (dst *UnRegisterAppReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnRegisterAppReq.Merge(dst, src)
}
func (m *UnRegisterAppReq) XXX_Size() int {
	return xxx_messageInfo_UnRegisterAppReq.Size(m)
}
func (m *UnRegisterAppReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnRegisterAppReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnRegisterAppReq proto.InternalMessageInfo

func (m *UnRegisterAppReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

type UnRegisterAppRsp struct {
	Common               *CommonRsp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UnRegisterAppRsp) Reset()         { *m = UnRegisterAppRsp{} }
func (m *UnRegisterAppRsp) String() string { return proto.CompactTextString(m) }
func (*UnRegisterAppRsp) ProtoMessage()    {}
func (*UnRegisterAppRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{16}
}
func (m *UnRegisterAppRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnRegisterAppRsp.Unmarshal(m, b)
}
func (m *UnRegisterAppRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnRegisterAppRsp.Marshal(b, m, deterministic)
}
func (dst *UnRegisterAppRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnRegisterAppRsp.Merge(dst, src)
}
func (m *UnRegisterAppRsp) XXX_Size() int {
	return xxx_messageInfo_UnRegisterAppRsp.Size(m)
}
func (m *UnRegisterAppRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnRegisterAppRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UnRegisterAppRsp proto.InternalMessageInfo

func (m *UnRegisterAppRsp) GetCommon() *CommonRsp {
	if m != nil {
		return m.Common
	}
	return nil
}

type RegisterLDAPAccountReq struct {
	Common               *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Email                string     `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterLDAPAccountReq) Reset()         { *m = RegisterLDAPAccountReq{} }
func (m *RegisterLDAPAccountReq) String() string { return proto.CompactTextString(m) }
func (*RegisterLDAPAccountReq) ProtoMessage()    {}
func (*RegisterLDAPAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{17}
}
func (m *RegisterLDAPAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterLDAPAccountReq.Unmarshal(m, b)
}
func (m *RegisterLDAPAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterLDAPAccountReq.Marshal(b, m, deterministic)
}
func (dst *RegisterLDAPAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterLDAPAccountReq.Merge(dst, src)
}
func (m *RegisterLDAPAccountReq) XXX_Size() int {
	return xxx_messageInfo_RegisterLDAPAccountReq.Size(m)
}
func (m *RegisterLDAPAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterLDAPAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterLDAPAccountReq proto.InternalMessageInfo

func (m *RegisterLDAPAccountReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *RegisterLDAPAccountReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterLDAPAccountRsp struct {
	Common               *CommonRsp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	AccountId            string     `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterLDAPAccountRsp) Reset()         { *m = RegisterLDAPAccountRsp{} }
func (m *RegisterLDAPAccountRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterLDAPAccountRsp) ProtoMessage()    {}
func (*RegisterLDAPAccountRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{18}
}
func (m *RegisterLDAPAccountRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterLDAPAccountRsp.Unmarshal(m, b)
}
func (m *RegisterLDAPAccountRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterLDAPAccountRsp.Marshal(b, m, deterministic)
}
func (dst *RegisterLDAPAccountRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterLDAPAccountRsp.Merge(dst, src)
}
func (m *RegisterLDAPAccountRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterLDAPAccountRsp.Size(m)
}
func (m *RegisterLDAPAccountRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterLDAPAccountRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterLDAPAccountRsp proto.InternalMessageInfo

func (m *RegisterLDAPAccountRsp) GetCommon() *CommonRsp {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *RegisterLDAPAccountRsp) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type RegisterLocalAccountReq struct {
	Common               *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Email                string     `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	UserName             string     `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	DisplayName          string     `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Password             string     `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterLocalAccountReq) Reset()         { *m = RegisterLocalAccountReq{} }
func (m *RegisterLocalAccountReq) String() string { return proto.CompactTextString(m) }
func (*RegisterLocalAccountReq) ProtoMessage()    {}
func (*RegisterLocalAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{19}
}
func (m *RegisterLocalAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterLocalAccountReq.Unmarshal(m, b)
}
func (m *RegisterLocalAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterLocalAccountReq.Marshal(b, m, deterministic)
}
func (dst *RegisterLocalAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterLocalAccountReq.Merge(dst, src)
}
func (m *RegisterLocalAccountReq) XXX_Size() int {
	return xxx_messageInfo_RegisterLocalAccountReq.Size(m)
}
func (m *RegisterLocalAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterLocalAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterLocalAccountReq proto.InternalMessageInfo

func (m *RegisterLocalAccountReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *RegisterLocalAccountReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterLocalAccountReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterLocalAccountReq) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *RegisterLocalAccountReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterLocalAccountRsp struct {
	Common               *CommonRsp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	AccountId            string     `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterLocalAccountRsp) Reset()         { *m = RegisterLocalAccountRsp{} }
func (m *RegisterLocalAccountRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterLocalAccountRsp) ProtoMessage()    {}
func (*RegisterLocalAccountRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{20}
}
func (m *RegisterLocalAccountRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterLocalAccountRsp.Unmarshal(m, b)
}
func (m *RegisterLocalAccountRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterLocalAccountRsp.Marshal(b, m, deterministic)
}
func (dst *RegisterLocalAccountRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterLocalAccountRsp.Merge(dst, src)
}
func (m *RegisterLocalAccountRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterLocalAccountRsp.Size(m)
}
func (m *RegisterLocalAccountRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterLocalAccountRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterLocalAccountRsp proto.InternalMessageInfo

func (m *RegisterLocalAccountRsp) GetCommon() *CommonRsp {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *RegisterLocalAccountRsp) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type UnRegisterAccountReq struct {
	Common               *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	AccountId            string     `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UnRegisterAccountReq) Reset()         { *m = UnRegisterAccountReq{} }
func (m *UnRegisterAccountReq) String() string { return proto.CompactTextString(m) }
func (*UnRegisterAccountReq) ProtoMessage()    {}
func (*UnRegisterAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{21}
}
func (m *UnRegisterAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnRegisterAccountReq.Unmarshal(m, b)
}
func (m *UnRegisterAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnRegisterAccountReq.Marshal(b, m, deterministic)
}
func (dst *UnRegisterAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnRegisterAccountReq.Merge(dst, src)
}
func (m *UnRegisterAccountReq) XXX_Size() int {
	return xxx_messageInfo_UnRegisterAccountReq.Size(m)
}
func (m *UnRegisterAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnRegisterAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnRegisterAccountReq proto.InternalMessageInfo

func (m *UnRegisterAccountReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *UnRegisterAccountReq) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type UnRegisterAccountRsp struct {
	Common               *CommonRsp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UnRegisterAccountRsp) Reset()         { *m = UnRegisterAccountRsp{} }
func (m *UnRegisterAccountRsp) String() string { return proto.CompactTextString(m) }
func (*UnRegisterAccountRsp) ProtoMessage()    {}
func (*UnRegisterAccountRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{22}
}
func (m *UnRegisterAccountRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnRegisterAccountRsp.Unmarshal(m, b)
}
func (m *UnRegisterAccountRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnRegisterAccountRsp.Marshal(b, m, deterministic)
}
func (dst *UnRegisterAccountRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnRegisterAccountRsp.Merge(dst, src)
}
func (m *UnRegisterAccountRsp) XXX_Size() int {
	return xxx_messageInfo_UnRegisterAccountRsp.Size(m)
}
func (m *UnRegisterAccountRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnRegisterAccountRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UnRegisterAccountRsp proto.InternalMessageInfo

func (m *UnRegisterAccountRsp) GetCommon() *CommonRsp {
	if m != nil {
		return m.Common
	}
	return nil
}

type GetAccountInfoReq struct {
	Common               *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	AccountId            string     `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountInfoReq) Reset()         { *m = GetAccountInfoReq{} }
func (m *GetAccountInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetAccountInfoReq) ProtoMessage()    {}
func (*GetAccountInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{23}
}
func (m *GetAccountInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountInfoReq.Unmarshal(m, b)
}
func (m *GetAccountInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountInfoReq.Marshal(b, m, deterministic)
}
func (dst *GetAccountInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountInfoReq.Merge(dst, src)
}
func (m *GetAccountInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetAccountInfoReq.Size(m)
}
func (m *GetAccountInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountInfoReq proto.InternalMessageInfo

func (m *GetAccountInfoReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *GetAccountInfoReq) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type GetAccountInfoRsp struct {
	Common               *CommonRsp   `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	AccountInfo          *AccountInfo `protobuf:"bytes,2,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetAccountInfoRsp) Reset()         { *m = GetAccountInfoRsp{} }
func (m *GetAccountInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetAccountInfoRsp) ProtoMessage()    {}
func (*GetAccountInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{24}
}
func (m *GetAccountInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountInfoRsp.Unmarshal(m, b)
}
func (m *GetAccountInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountInfoRsp.Marshal(b, m, deterministic)
}
func (dst *GetAccountInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountInfoRsp.Merge(dst, src)
}
func (m *GetAccountInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetAccountInfoRsp.Size(m)
}
func (m *GetAccountInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountInfoRsp proto.InternalMessageInfo

func (m *GetAccountInfoRsp) GetCommon() *CommonRsp {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *GetAccountInfoRsp) GetAccountInfo() *AccountInfo {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

type GetAccountCountReq struct {
	Common               *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountCountReq) Reset()         { *m = GetAccountCountReq{} }
func (m *GetAccountCountReq) String() string { return proto.CompactTextString(m) }
func (*GetAccountCountReq) ProtoMessage()    {}
func (*GetAccountCountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{25}
}
func (m *GetAccountCountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountCountReq.Unmarshal(m, b)
}
func (m *GetAccountCountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountCountReq.Marshal(b, m, deterministic)
}
func (dst *GetAccountCountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountCountReq.Merge(dst, src)
}
func (m *GetAccountCountReq) XXX_Size() int {
	return xxx_messageInfo_GetAccountCountReq.Size(m)
}
func (m *GetAccountCountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountCountReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountCountReq proto.InternalMessageInfo

func (m *GetAccountCountReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

type GetAccountCountRsp struct {
	Common               *CommonRsp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Count                int32      `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountCountRsp) Reset()         { *m = GetAccountCountRsp{} }
func (m *GetAccountCountRsp) String() string { return proto.CompactTextString(m) }
func (*GetAccountCountRsp) ProtoMessage()    {}
func (*GetAccountCountRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{26}
}
func (m *GetAccountCountRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountCountRsp.Unmarshal(m, b)
}
func (m *GetAccountCountRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountCountRsp.Marshal(b, m, deterministic)
}
func (dst *GetAccountCountRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountCountRsp.Merge(dst, src)
}
func (m *GetAccountCountRsp) XXX_Size() int {
	return xxx_messageInfo_GetAccountCountRsp.Size(m)
}
func (m *GetAccountCountRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountCountRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountCountRsp proto.InternalMessageInfo

func (m *GetAccountCountRsp) GetCommon() *CommonRsp {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *GetAccountCountRsp) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetAccountListReq struct {
	Common               *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	StartIndex           int32      `protobuf:"varint,2,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"`
	Count                int32      `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountListReq) Reset()         { *m = GetAccountListReq{} }
func (m *GetAccountListReq) String() string { return proto.CompactTextString(m) }
func (*GetAccountListReq) ProtoMessage()    {}
func (*GetAccountListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{27}
}
func (m *GetAccountListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountListReq.Unmarshal(m, b)
}
func (m *GetAccountListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountListReq.Marshal(b, m, deterministic)
}
func (dst *GetAccountListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountListReq.Merge(dst, src)
}
func (m *GetAccountListReq) XXX_Size() int {
	return xxx_messageInfo_GetAccountListReq.Size(m)
}
func (m *GetAccountListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountListReq proto.InternalMessageInfo

func (m *GetAccountListReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *GetAccountListReq) GetStartIndex() int32 {
	if m != nil {
		return m.StartIndex
	}
	return 0
}

func (m *GetAccountListReq) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetAccountListRsp struct {
	Common               *CommonRsp     `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	AccountInfoList      []*AccountInfo `protobuf:"bytes,2,rep,name=account_info_list,json=accountInfoList,proto3" json:"account_info_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetAccountListRsp) Reset()         { *m = GetAccountListRsp{} }
func (m *GetAccountListRsp) String() string { return proto.CompactTextString(m) }
func (*GetAccountListRsp) ProtoMessage()    {}
func (*GetAccountListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_876fd612a1d0d9f6, []int{28}
}
func (m *GetAccountListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountListRsp.Unmarshal(m, b)
}
func (m *GetAccountListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountListRsp.Marshal(b, m, deterministic)
}
func (dst *GetAccountListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountListRsp.Merge(dst, src)
}
func (m *GetAccountListRsp) XXX_Size() int {
	return xxx_messageInfo_GetAccountListRsp.Size(m)
}
func (m *GetAccountListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountListRsp proto.InternalMessageInfo

func (m *GetAccountListRsp) GetCommon() *CommonRsp {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *GetAccountListRsp) GetAccountInfoList() []*AccountInfo {
	if m != nil {
		return m.AccountInfoList
	}
	return nil
}

func init() {
	proto.RegisterType((*CommonReq)(nil), "pb.CommonReq")
	proto.RegisterType((*CommonRsp)(nil), "pb.CommonRsp")
	proto.RegisterType((*AccountInfo)(nil), "pb.AccountInfo")
	proto.RegisterType((*SetSessionUserDataRsp)(nil), "pb.SetSessionUserDataRsp")
	proto.RegisterType((*GetSessionUserDataReq)(nil), "pb.GetSessionUserDataReq")
	proto.RegisterType((*GetSessionUserDataRsp)(nil), "pb.GetSessionUserDataRsp")
	proto.RegisterType((*LoginReq)(nil), "pb.LoginReq")
	proto.RegisterType((*LoginRsp)(nil), "pb.LoginRsp")
	proto.RegisterType((*LogoutReq)(nil), "pb.LogoutReq")
	proto.RegisterType((*LogoutRsp)(nil), "pb.LogoutRsp")
	proto.RegisterType((*GetSessionInfoReq)(nil), "pb.GetSessionInfoReq")
	proto.RegisterType((*GetSessionInfoRsp)(nil), "pb.GetSessionInfoRsp")
	proto.RegisterType((*SetSessionUserDataReq)(nil), "pb.SetSessionUserDataReq")
	proto.RegisterType((*RegisterAppReq)(nil), "pb.RegisterAppReq")
	proto.RegisterType((*RegisterAppRsp)(nil), "pb.RegisterAppRsp")
	proto.RegisterType((*UnRegisterAppReq)(nil), "pb.UnRegisterAppReq")
	proto.RegisterType((*UnRegisterAppRsp)(nil), "pb.UnRegisterAppRsp")
	proto.RegisterType((*RegisterLDAPAccountReq)(nil), "pb.RegisterLDAPAccountReq")
	proto.RegisterType((*RegisterLDAPAccountRsp)(nil), "pb.RegisterLDAPAccountRsp")
	proto.RegisterType((*RegisterLocalAccountReq)(nil), "pb.RegisterLocalAccountReq")
	proto.RegisterType((*RegisterLocalAccountRsp)(nil), "pb.RegisterLocalAccountRsp")
	proto.RegisterType((*UnRegisterAccountReq)(nil), "pb.UnRegisterAccountReq")
	proto.RegisterType((*UnRegisterAccountRsp)(nil), "pb.UnRegisterAccountRsp")
	proto.RegisterType((*GetAccountInfoReq)(nil), "pb.GetAccountInfoReq")
	proto.RegisterType((*GetAccountInfoRsp)(nil), "pb.GetAccountInfoRsp")
	proto.RegisterType((*GetAccountCountReq)(nil), "pb.GetAccountCountReq")
	proto.RegisterType((*GetAccountCountRsp)(nil), "pb.GetAccountCountRsp")
	proto.RegisterType((*GetAccountListReq)(nil), "pb.GetAccountListReq")
	proto.RegisterType((*GetAccountListRsp)(nil), "pb.GetAccountListRsp")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_msg_876fd612a1d0d9f6) }

var fileDescriptor_msg_876fd612a1d0d9f6 = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0xb3, 0xb5, 0x6b, 0x6e, 0xf6, 0xc1, 0xa2, 0x6d, 0x14, 0x10, 0x02, 0x2c, 0x81, 0x78,
	0xda, 0x43, 0x79, 0xe0, 0x63, 0x02, 0x54, 0x6d, 0xd2, 0x54, 0xa9, 0x42, 0x90, 0xaa, 0x0f, 0x08,
	0x44, 0xe5, 0xc6, 0x5e, 0x65, 0x68, 0x6c, 0x37, 0x4e, 0x35, 0xe0, 0x2f, 0xf0, 0x6f, 0xf8, 0x85,
	0xc8, 0xce, 0x47, 0xd3, 0xa6, 0x94, 0x04, 0xca, 0xe3, 0xb5, 0x7b, 0xee, 0xb9, 0xf7, 0xf8, 0xf4,
	0xb4, 0x60, 0x07, 0x6a, 0x7c, 0x2a, 0x43, 0x11, 0x09, 0xd7, 0x92, 0x23, 0xf4, 0x0c, 0xec, 0x73,
	0x11, 0x04, 0x82, 0x7b, 0x74, 0xea, 0x1e, 0x43, 0x03, 0x4b, 0x39, 0x64, 0xa4, 0x55, 0xbb, 0x5f,
	0x7b, 0x6c, 0x7b, 0x75, 0x2c, 0x65, 0x97, 0xb8, 0x47, 0x50, 0x8f, 0xc4, 0x17, 0xca, 0x5b, 0x56,
	0x7c, 0x6a, 0x0a, 0xf4, 0x3a, 0x43, 0x2a, 0xe9, 0xb6, 0x60, 0x47, 0xcd, 0x7c, 0x9f, 0x2a, 0x65,
	0xa0, 0x4d, 0x2f, 0x2d, 0xf5, 0x4d, 0x40, 0x95, 0xc2, 0x63, 0x9a, 0xc0, 0xd3, 0x12, 0xfd, 0xa8,
	0x81, 0xd3, 0xf1, 0x7d, 0x31, 0xe3, 0x51, 0x97, 0x5f, 0x09, 0x77, 0x1f, 0xac, 0x8c, 0xd9, 0x62,
	0xc4, 0x3d, 0x81, 0x06, 0x11, 0x01, 0x66, 0x29, 0x6f, 0x52, 0xb9, 0x77, 0xc0, 0x9e, 0x29, 0x1a,
	0x0e, 0x39, 0x0e, 0x68, 0x6b, 0xcb, 0x5c, 0x35, 0xf5, 0xc1, 0x1b, 0x1c, 0x50, 0x3d, 0x2b, 0x0d,
	0x30, 0x9b, 0xb4, 0xb6, 0xe3, 0x59, 0x4d, 0xe1, 0x3e, 0x80, 0x5d, 0xc2, 0x94, 0x9c, 0xe0, 0x6f,
	0x31, 0xaa, 0x6e, 0x2e, 0x9d, 0xe4, 0x4c, 0x03, 0xd1, 0x2b, 0x38, 0xee, 0xd3, 0xa8, 0x4f, 0x95,
	0x62, 0x82, 0x0f, 0x14, 0x0d, 0x2f, 0x70, 0x84, 0xf5, 0x6a, 0x0f, 0xa1, 0xe1, 0x9b, 0x3d, 0xcd,
	0x68, 0x4e, 0x7b, 0xef, 0x54, 0x8e, 0x4e, 0xb3, 0xcd, 0xbd, 0xe4, 0x52, 0xe3, 0x2f, 0x8b, 0x78,
	0x3a, 0x5d, 0x8b, 0xa7, 0xd3, 0x0c, 0xff, 0x61, 0x25, 0xbe, 0x34, 0x7f, 0xa6, 0x0a, 0xc1, 0x11,
	0x4e, 0x04, 0x33, 0xaa, 0xe8, 0x36, 0xe8, 0x33, 0x34, 0x7b, 0x62, 0xcc, 0x78, 0xf9, 0x79, 0x16,
	0x55, 0xb6, 0x96, 0x54, 0xbe, 0x0d, 0x4d, 0x89, 0x95, 0xba, 0x16, 0x21, 0x49, 0x5f, 0x20, 0xad,
	0xd1, 0x65, 0xca, 0x55, 0x7e, 0xf6, 0xd5, 0x06, 0x6b, 0x83, 0xdd, 0x13, 0x63, 0x31, 0x8b, 0x2a,
	0xa8, 0x38, 0xc7, 0x94, 0x7f, 0xb9, 0x17, 0x70, 0x38, 0x57, 0x5e, 0x3b, 0xb1, 0x02, 0x1f, 0x2f,
	0x60, 0xcb, 0x6f, 0xdd, 0x86, 0x5d, 0x1c, 0xdb, 0x7f, 0xc8, 0xf8, 0x95, 0x30, 0xcb, 0x3b, 0xed,
	0x03, 0xfd, 0xe1, 0xdc, 0xd7, 0xc2, 0x73, 0xf0, 0xbc, 0xd0, 0x2e, 0xe9, 0xff, 0x83, 0xcb, 0xd6,
	0xbb, 0xe4, 0x3b, 0xec, 0x7b, 0x74, 0xcc, 0x54, 0x44, 0xc3, 0x8e, 0x94, 0x15, 0xba, 0xde, 0x82,
	0xa6, 0xce, 0x8d, 0x9c, 0x55, 0x76, 0xb0, 0x94, 0xc6, 0x29, 0x8f, 0xe0, 0x40, 0x5f, 0x85, 0x94,
	0xb0, 0x90, 0xfa, 0x91, 0xce, 0x96, 0xd8, 0x30, 0x7b, 0x58, 0x53, 0xc4, 0xa7, 0x5d, 0x82, 0x9e,
	0x2e, 0x72, 0x97, 0x7f, 0xbd, 0xe7, 0x70, 0x63, 0xc0, 0xff, 0x6a, 0xec, 0x22, 0xb4, 0x3c, 0xeb,
	0x00, 0x4e, 0x52, 0x60, 0xef, 0xa2, 0xf3, 0x36, 0x79, 0xaf, 0x0a, 0x92, 0x65, 0x39, 0x65, 0xe5,
	0x72, 0x0a, 0x7d, 0x5a, 0xdd, 0xb6, 0xbc, 0xa7, 0xee, 0x02, 0x64, 0x9e, 0x22, 0x49, 0x6f, 0x3b,
	0x35, 0x10, 0x41, 0x3f, 0x6b, 0x70, 0x33, 0x23, 0x10, 0x3e, 0x9e, 0x6c, 0x68, 0xf0, 0xf5, 0x99,
	0xbc, 0x9c, 0xbe, 0xdb, 0x85, 0xf4, 0x5d, 0x08, 0x94, 0xfa, 0x52, 0xa0, 0x0c, 0x7f, 0x33, 0xf3,
	0xc6, 0x54, 0xf9, 0x08, 0x47, 0x39, 0x1f, 0x54, 0x56, 0xe4, 0x0f, 0xdd, 0x5f, 0xae, 0xea, 0x5e,
	0xde, 0x69, 0xef, 0x4d, 0xc2, 0xe4, 0x03, 0x61, 0x63, 0x93, 0xf1, 0x42, 0xeb, 0xff, 0x1b, 0x5e,
	0x67, 0xe0, 0xce, 0xf9, 0xce, 0xab, 0xa9, 0x8c, 0xde, 0x15, 0xc1, 0x95, 0x7e, 0x60, 0x0c, 0xce,
	0x8c, 0x59, 0xf7, 0xe2, 0x02, 0x4d, 0xf3, 0xfb, 0xf7, 0x98, 0xaa, 0xf2, 0xe8, 0xf7, 0xc0, 0x51,
	0x11, 0x0e, 0xf5, 0xf6, 0x84, 0x7e, 0x4d, 0xfa, 0x82, 0x39, 0xea, 0xea, 0x93, 0x39, 0xe5, 0x56,
	0x9e, 0xf2, 0xba, 0x40, 0x59, 0x7e, 0x89, 0x33, 0x38, 0xcc, 0x4b, 0x3e, 0x9c, 0x30, 0xa5, 0x17,
	0xda, 0x5a, 0xa5, 0xfb, 0x41, 0x4e, 0x77, 0x4d, 0x33, 0x6a, 0x98, 0xbf, 0x7c, 0x4f, 0x7e, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x1b, 0xec, 0xba, 0x83, 0xff, 0x09, 0x00, 0x00,
}
