// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7dc4d5d85c
// Version Date: Mon May 28 22:12:59 UTC 2018

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "test/truss_test/pb"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC TestServer.
func MakeGRPCServer(endpoints Endpoints) pb.TestServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	return &grpcServer{
		// test

		hello: grpctransport.NewServer(
			endpoints.HelloEndpoint,
			DecodeGRPCHelloRequest,
			EncodeGRPCHelloResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the TestServer interface
type grpcServer struct {
	hello grpctransport.Handler
}

// Methods for grpcServer to implement TestServer interface

func (s *grpcServer) Hello(ctx context.Context, req *pb.Request) (*pb.Response, error) {
	_, rep, err := s.hello.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.Response), nil
}

// Server Decode

// DecodeGRPCHelloRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC hello request to a user-domain hello request. Primarily useful in a server.
func DecodeGRPCHelloRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.Request)
	return req, nil
}

// Server Encode

// EncodeGRPCHelloResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain hello response to a gRPC hello reply. Primarily useful in a server.
func EncodeGRPCHelloResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.Response)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
