// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7dc4d5d85c
// Version Date: Mon May 28 22:12:59 UTC 2018

package handlers

import (
	pb "test/truss_test/pb"
)

// Hello implements Service.
func Hello(NameHello string) (*pb.Request, error) {
	request := pb.Request{
		Name: NameHello,
	}
	return &request, nil
}
