// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7dc4d5d85c
// Version Date: Mon May 28 22:12:59 UTC 2018

// Package grpc provides a gRPC client for the Test service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "test/truss_test/pb"
	"test/truss_test/test-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.TestServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var helloEndpoint endpoint.Endpoint
	{
		helloEndpoint = grpctransport.NewClient(
			conn,
			"pb.Test",
			"Hello",
			EncodeGRPCHelloRequest,
			DecodeGRPCHelloResponse,
			pb.Response{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		HelloEndpoint: helloEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCHelloResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC hello reply to a user-domain hello response. Primarily useful in a client.
func DecodeGRPCHelloResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.Response)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCHelloRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain hello request to a gRPC hello request. Primarily useful in a client.
func EncodeGRPCHelloRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.Request)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
